### ISSUE TITLE
Register as  PyPI utility

### ISSUE THREAD

**Issue by ogt** [ogt/pipdiff#1]
This is the odesk job description for this enhancement.

Register a python utility at PyPI
====
I need someone to do a small python-related task for me:

Task Description
-----

There is an existing single file utility - available as a public gist at https://gist.github.com/jzempel/4624227
I would like you to add it at PyPI so as I (or anyone else with python and pip installed) can install it and use it as follows
```
> pip install pipdiff
> pipdiff
Django==1.4.3                            PyPI:Django==1.5
Fabric==1.5.1                            PyPI:Fabric==1.6.0
...
zope.interface==4.0.3                    PyPI:zope.interface==4.0.5
>
```
Follow all the typical conventions for any information that may be required for the registration (licenses, authors, maintainers, platforms etc, e.g. see https://github.com/zacharyvoase/slugify  for a similar simple utility that was added to PyPI)
When you are done with the utility registration you will need to do the following additional steps:
1. Fork my repository https://github.com/ogt/pipdiff
2. Add in your forked repository all the pipdiff package files (feel free to completely remove my stuff)
3. Issue a pull request to me.
4. Create a public gist where you describe step by step what you did to register pipdiff. The purpose of this is a) so as I can do it next time myself and b) to understand any assumptions/decisions you made. Assume that you are giving instructions to a python programmer, comfortable with unix, that has often  used pip to install stuff but has never contributed anything to the public domain
5. Provide a link to the gist above in your pull request comment above.

Instructions to Applicants
-------
Please provide an one-line answer to the following 3 questions to be considered for the job: 
1. What does PyPI stand for.
2. Name 2 tools that developers often use togther with PyPI
3. When do you expect to have this done?

Do not under-or overbid. I think $20 is a reasonable pay for this job. I will pay exactly that amount to the person that does the job.

**Comment by ogt** [comment]
Hi @littlepea . I never got back to you with my user credentials - and I cant find your email (I only have the 2 yr old odesk messages). Do you mind a) either pushing the new 0.2 version to pypi or email-connecting with me ( odysseas at tsatalos dot com ) to switch owners?

**Comment by anthonydb** [comment]
Any update @littlepea?

**Comment by littlepea** [comment]
@ogt Done: https://pypi.python.org/pypi/pipdiff/0.2

Feel free to send me your PyPI username to switch owners

**Comment by ogt** [comment]
Thank you @littlepea 
My PyPi username is `odysseas`
